[package]
name = "prim-codegen"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
prim-compiler = { path = "../prim-compiler" }
prim-hir = { path = "../prim-hir" }
cranelift = "0.122"
cranelift-module = "0.122"
cranelift-object = "0.122"
cranelift-native = "0.122"
